### PR TITLE
Implement basic support for progress bar output.

### PR DESCRIPTION
**Pull request by ioquatix**
cc @olleolleolle 

Screen Recording 2020-07-27 at 12 28 14 AM-Animated Image (Large)

It's a really easy way to add a progress bar to anything and it goes out via the normal logging channels. In theory we could also write this out correctly as JSON etc.

### CODE REVIEW

**Comment by ioquatix** [comment]
I played around with some different formatting options:

Screen Recording 2020-07-27 at 12 28 14 AM-Animated Image (Large)

**Comment by ioquatix** [comment]
cc @madleech @bryanp @piotrmurach

**Comment by ioquatix** [comment]
The formatting of full height unicode blocks is a bit ugly.

**Comment by ioquatix** [comment]
It's logged at the info level. Here is the code that generated the gif:

``` ruby
	measure = Console.logger.measure("Progress Bar", 10000)
	
	10000.times do |i|
		sleep 0.001
		
		measure.increment
	end
```

**Comment by piotrmurach** [comment]
@ioquatix Looks good to me. Don't know much about the `console` gem but it sounds like a useful feature. Curious, what is your motivation behind implementing your own instead of using other gems like [tty-progressbar](https://github.com/piotrmurach/tty-progressbar)?

**Comment by olleolleolle** [comment]
Neat output!

**Comment by ioquatix** [comment]
@piotrmurach I really like `tty-progressbar` but the scope of that gem is bigger and a little bit different from what I wanted here. This gem is a dependency of many others and thus pulling in an extra dependency would have a big impact. The total implementation of the progress bar rendering using unicode is maybe 10 lines?

**Comment by bryanp** [comment]
Really cool! It first seemed out of scope since `console` is for logging, but it makes sense after looking at it.

**Comment by ioquatix** [comment]
@bryanp I agree, at first I didn't know if it was a good idea, but in practice it's super useful... because logging progress is actually much more common and I realised I was just implementing crappy progress bars in all my code.

**Comment by ioquatix** [comment]
I could use the terminal background color to make the progress bar look a bit more boxy:

image

**Pull request merged**
